import { withAuthUser, useAuthUser } from "next-firebase-auth";
import Head from "next/head";
import styles from "../styles/Register.module.css";
import { useState } from "react";
import { MoonLoader } from "react-spinners";
import { callRegisterApi } from "./api/register";

export default withAuthUser()(function Register() {
  const authUser = useAuthUser();
  const [email, setEmail] = useState<string>("");
  const [password, setPassword] = useState<string>("");
  const [confirmPassword, setConfirmPassword] = useState<string>("");
  const [fullName, setFullName] = useState<string>("");
  const [displayName, setDisplayName] = useState<string>("");
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const register = async () => {
    setIsLoading(true);
    if (password !== confirmPassword) {
      alert("Password confirmation mismatch");
      setIsLoading(false);
      return;
    }
    const resp = await callRegisterApi(authUser, {
      email,
      password,
      fullname: fullName,
      displayname: displayName,
    });
    if (!resp?.message) {
      alert(resp?.error);
    }
    setIsLoading(false);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Register</h1>

        <p className={styles.description}>Tell us who you are!</p>

        <div className={styles.card}>
          <h3 className={styles.inputhead}>Email</h3>
          <input
            type="email"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            className={styles.input}
          />
          <h3 className={styles.inputhead}>Password</h3>
          <input
            type="password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            className={styles.input}
          />
          <h3 className={styles.inputhead}>Confirm Password</h3>
          <input
            type="password"
            value={confirmPassword}
            onChange={(e) => setConfirmPassword(e.target.value)}
            className={styles.input}
          />
          <h3 className={styles.inputhead}>Full Name</h3>
          <input
            type="text"
            value={fullName}
            onChange={(e) => setFullName(e.target.value)}
            className={styles.input}
          />
          <h3 className={styles.inputhead}>Display Name</h3>
          <input
            type="text"
            value={displayName}
            onChange={(e) => setDisplayName(e.target.value)}
            className={styles.input}
          />
          <button
            className={styles.button}
            onClick={register}
            disabled={isLoading}
          >
            {isLoading ? (
              <div className={styles.spinnerwrapper}>
                <MoonLoader size="15px" color="white" css="display: block" />
              </div>
            ) : (
              <>Register</>
            )}
          </button>
        </div>
      </main>
    </div>
  );
});
